//This class manages the execution of the optimal filter. It contains a vector of all possible optimal filters for a given partition of the parameter space (list_of).


#include <complex>
#include <vector>
#include "OptimalFilterNxM.h"
    

#ifndef OFMANAGERNXM_H  
#define OFMANAGERNXM_H  


class OFManagerNxM{
    
    public:

    int num_templates;      //number of all templates generated by TemplateGeneratorNxm class
    int num_channels;
    int num_bins_t;
    
    std::vector<std::vector<std::complex<double>>> J;

    double E_min;
    double E_max;

    std::vector<std::vector<std::vector<std::vector<double>>>> map_bins_part;   //this map_bins_part is specific to the OFManagerNxM class and only contains specific parts of the map_bins_part in TemplateGeneratorNxM Class, decided by i%3==0.
    std::vector<OptimalFilterNxM> list_of;                //list of all possible OptimalFilterNxM objects that might be needed

    int last_of_index;

    OFManagerNxM(double DT, double T_PRE, std::vector<std::vector<std::vector<std::complex<double>>>> TEMPLATES, std::vector<std::vector<std::vector<std::complex<double>>>> V, double E_MIN, double E_MAX, std::vector<std::vector<std::vector<std::vector<double>>>> MAP_BINS_PART);
    int ProcessEvent(std::vector<std::vector<std::complex<double>>> S, std::vector<std::vector<double>> &result);
    void Draw(std::string path, int event_count);

};



#endif